#!/usr/bin/bash

SRC=/home/marxin/Programming/texi2rst-generated/sphinx/
DST=gccroot/

rm -rf $DST

mkdir -p $DST/gcc/doc
cp -r $SRC/gcc $DST/gcc/doc
cp -r $SRC/gccint $DST/gcc/doc
cp -r $SRC/cpp $DST/gcc/doc
cp -r $SRC/cppinternals $DST/gcc/doc
cp -r $SRC/install $DST/gcc/doc

mkdir -p $DST/gcc/go
cp -r $SRC/gccgo $DST/gcc/go/doc

mkdir -p $DST/gcc/fortran/doc
cp -r $SRC/gfortran $DST/gcc/fortran/doc
cp -r $SRC/gfc-internals $DST/gcc/fortran/doc/

mkdir -p $DST/gcc/d/doc
cp -r $SRC/gccgo $DST/gcc/d/doc

mkdir -p $DST/libgomp
cp -r $SRC/libgomp $DST/libgomp/doc

mkdir -p $DST/libitm
cp -r $SRC/libitm $DST/libitm/doc

mkdir -p $DST/libquadmath
cp -r $SRC/libquadmath $DST/libquadmath/doc

mkdir -p $DST/libiberty
cp -r $SRC/libiberty $DST/libiberty/doc

mkdir -p $DST/doc
cp -r $SRC/share/* $DST/doc
cp $SRC/baseconf.py $DST/doc

./strip.py $DST

cp $SRC/gcc/Makefile /tmp/Makefile
find $DST -name Makefile | xargs rm
mv /tmp/Makefile $DST/doc
