name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: marxin/opensuse-texi2rst
      options: --privileged

    steps:
      - uses: actions/checkout@v2
      - run: pytest
      - run: flake8 node.py texi2rst.py

  generate_rst:
    runs-on: ubuntu-latest
    container:
      image: marxin/opensuse-texi2rst
      options: --privileged

    steps:
      - uses: actions/checkout@v2
      - run: nproc
      - name: Setup git config
        run: |
          git config --global user.email mliska@suse.cz
          git config --global user.name marxin
      - name: Clone generated repository
        run: git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/marxin/texi2rst-generated.git
      - run: make latexpdf -j`nproc` || makeindex ./_build/latex/gdc.idx
        working-directory: texi2rst-generated/sphinx/gdc
