name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: marxin/opensuse-texi2rst

    steps:
      - uses: actions/checkout@v2
      - run: pytest
      - run: flake8 node.py texi2rst.py

  generate_rst:
    runs-on: ubuntu-latest
    container:
      image: marxin/opensuse-texi2rst
    env:
      SPHINXBUILD: /tmp/venv/bin/sphinx-build

    steps:
      - uses: actions/checkout@v2
      - run: nproc
      - run: xindy --version || true
      - run: virtualenv /tmp/venv
      - run: |
          git clone https://github.com/sphinx-doc/sphinx.git
          cd sphinx
          /tmp/venv/bin/pip install -e .
          /tmp/venv/bin/pip install sphinx_rtd_theme furo sphinx-copybutton
      - name: Clone GCC
        run: git clone --depth 1 --branch devel/sphinx git://gcc.gnu.org/git/gcc.git
        working-directory: scripts
      - name: Generate XML files from TEXI
        run: ./generate-xml.py gcc objdir xml
        working-directory: scripts
      - name: Generate RST files from XML
        run: ./generate-rst.py xml sphinx
        working-directory: scripts
      - name: Create shared RST files
        run: ./create-shared-files.py sphinx
        working-directory: scripts
      - name: Add copyright
        run: ./add-copyright.py sphinx
        working-directory: scripts
      - name: Copy demo project
        run: cp -r templates/demo sphinx && cp templates/Makefile sphinx/demo
        working-directory: scripts
      - run: du -hs sphinx
        working-directory: scripts
      - name: Setup git config
        run: |
          git config --global user.email mliska@suse.cz
          git config --global user.name marxin
      - name: Clone generated repository
        run: git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/marxin/texi2rst-generated.git
      - name: Change branch (pull request)
        run: |
          git checkout raw
          git checkout -b ${{ github.head_ref }}
          git push --set-upstream origin ${{ github.head_ref }} -f
        if: github.ref != 'refs/heads/master'
        working-directory: texi2rst-generated
      - name: Change branch (raw)
        run: |
          git checkout raw
        if: github.ref == 'refs/heads/master'
        working-directory: texi2rst-generated
      - name: Modify generated repository
        run: |
          rm -rf sphinx
          cp -r ../scripts/sphinx .
          cp ../scripts/templates/index.html sphinx
          git add sphinx/*
          echo ${{ github.sha }} > REVISION
          git add REVISION
          date > DATESTAMP
          git add DATESTAMP
          git commit -a -m "Built (${{ github.event_name }}) ${{ github.repository }}@${{ github.sha }}"
          git push
          echo "output_sha=`git rev-parse HEAD`" >> $GITHUB_ENV
        working-directory: texi2rst-generated
      - name: Update master and push
        run: |
          git checkout master
          git merge raw
          git push origin master
        working-directory: texi2rst-generated
        if: github.ref == 'refs/heads/master'
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            It is published here: https://github.com/marxin/texi2rst-generated/commit/${{ env.output_sha }}
        if: github.ref != 'refs/heads/master'
      - name: Dry merge with master
        run: git merge master
        if: github.ref != 'refs/heads/master'
        working-directory: texi2rst-generated
      - run: make html -j`nproc` ${{ env.SPHINXBUILD }}
        working-directory: texi2rst-generated/sphinx
        if: github.ref == 'refs/heads/master'
      - run: make latexpdf -j`nproc ${{ env.SPHINXBUILD }}`
        working-directory: texi2rst-generated/sphinx
        if: github.ref == 'refs/heads/master'
      - run: make man -j`nproc ${{ env.SPHINXBUILD }}`
        working-directory: texi2rst-generated/sphinx
        if: github.ref == 'refs/heads/master'
      - run: du -hs texi2rst-generated/sphinx
        if: github.ref == 'refs/heads/master'
      - name: Convert manual pages to HTML
        run: find . -name '*.[17]' | xargs -i bash -c "groff -mandoc -Thtml {} > {}.html"
        working-directory: texi2rst-generated/sphinx
        if: github.ref == 'refs/heads/master'
      - run: make info -j`nproc ${{ env.SPHINXBUILD }}`
        working-directory: texi2rst-generated/sphinx
        if: github.ref == 'refs/heads/master'
      - run: rm -rf scripts && mv texi2rst-generated scripts
        if: github.ref == 'refs/heads/master'
      - name: Upload generated files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "scripts/sphinx"
          target: "/srv/www/htdocs/splichaleu/"
        if: github.ref == 'refs/heads/master'
