name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: "marxin/opensuse-texi2rst"

    steps:
      - uses: actions/checkout@v2
      - run: pytest
      - run: flake8 node.py texi2rst.py

  generate_rst:
    runs-on: ubuntu-latest
    container: "marxin/opensuse-texi2rst"

    steps:
      - uses: actions/checkout@v2
      - run: nproc
      - name: Clone GCC
        run: git clone --depth 1 --branch devel/sphinx git://gcc.gnu.org/git/gcc.git
        working-directory: scripts
      - name: Generate XML files from TEXI
        run: ./generate-xml.py gcc objdir xml
        working-directory: scripts
      - name: Generate RST files from XML
        run: ./generate-rst.py xml sphinx
        working-directory: scripts
      - run: du -hs sphinx
        working-directory: scripts
      - name: Setup git config
        run: |
          git config --global user.email mliska@suse.cz
          git config --global user.name marxin
      - name: Clone generated repository
        run: git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/marxin/texi2rst-generated.git
      - name: Change branch
        run: |
          git checkout -b ${{ github.head_ref }}
          git push --set-upstream origin ${{ github.head_ref }} -f
        if: github.ref != 'refs/heads/master'
        working-directory: texi2rst-generated
      - name: Modify generated repository
        run: |
          rm -rf sphinx
          cp -r ../scripts/sphinx .
          git add sphinx/*
          echo ${{ github.sha }} > REVISION
          git add REVISION
          git commit -a -m "Built (${{ github.event_name }}) ${{ github.repository }}@${{ github.sha }}"
          git push
          echo "output_sha=`git rev-parse HEAD`" >> $GITHUB_ENV
        working-directory: texi2rst-generated
      - run: cp templates/index.html sphinx
        working-directory: scripts
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            It is published here: https://github.com/marxin/texi2rst-generated/commit/${{ env.output_sha }}
        if: github.ref != 'refs/heads/master'
      - run: make html -j`nproc`
        working-directory: scripts/sphinx
        if: github.ref == 'refs/heads/master'
        # FIXME: remove all Warnings that make latexpdf return non-zero error code
      - run: make latexpdf -j`nproc` || true
        working-directory: scripts/sphinx
        if: github.ref == 'refs/heads/master'
      - run: make man -j`nproc`
        working-directory: scripts/sphinx
        if: github.ref == 'refs/heads/master'
      - run: du -hs scripts/sphinx
        if: github.ref == 'refs/heads/master'
      - name: Convert man pages to HTML
        run: find . -name '*.1' | xargs -i bash -c "groff -mandoc -Thtml {} > {}.html"
        working-directory: scripts/sphinx
        if: github.ref == 'refs/heads/master'
      - run: make info -j`nproc`
        working-directory: scripts/sphinx
        if: github.ref == 'refs/heads/master'
      - name: Upload generated files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "scripts/sphinx"
          target: "/srv/www/htdocs/splichaleu/"
        if: github.ref == 'refs/heads/master'
